### ISSUE TITLE
Not available from RubyGems

### ISSUE THREAD

**Issue by haffla** [KrugerHeavyIndustries/capistrano-backburner#2]
`gem install capistrano-backburner`

ERROR:  Could not find a valid gem 'capistrano-backburner' (>= 0) in any repository

**Comment by montdidier** [comment]
I never attempted to publish it to rubygems. You can use it directly from the repository. In the interim, I'll see if I can get it on rubygems.

**Comment by montdidier** [comment]
The current version 0.0.9 should be available from rubygems now. When I merge your [changes](https://github.com/KrugerHeavyIndustries/capistrano-backburner/pull/1), I will update the version on rubygems with your changes.
